server:
  port: 8080
spring:
  profiles:
    include:
      - jwt
      - oauth
  application:
    name: ClipStudio
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATABASE_HOST}:3306/clipstudio?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: true

#            scope:
#              - email
#              - profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/google #코드를 받을 주소 (토큰 받기 전) => 클라이언트 정보와 코드로 토큰을 발급받아야 함.
